In [1]:
import numpy as np

a. Create a 2D array based on the last 6 digits of your student ID (NIM). 

In [4]:
# 202310370311268

matrix = np.array ([[3, 1, 1], [2, 6, 8]])

print("matrix:")
print(matrix)

matrix:
[[3 1 1]
 [2 6 8]]


b. Perform addition, subtraction, and multiplication operations on the matrix you created. 

In [11]:
print("addition:")
print(matrix + matrix)

print("\nsubtraction:")
print(matrix - matrix)

print("\nmultiplication:")
print(matrix * 2)

addition:
[[ 6  2  2]
 [ 4 12 16]]

subtraction:
[[0 0 0]
 [0 0 0]]

multiplication:
[[ 6  2  2]
 [ 4 12 16]]


c. Convert the matrix into a 1D shape. 

In [12]:
matrix_1d = matrix.flatten()

print ("\nMatrix dalam bentuk 1D:")
print(matrix_1d)


Matrix dalam bentuk 1D:
[3 1 1 2 6 8]


d. Perform slicing on the matrix. 

In [ ]:
# Matrix 1D

print("\nAmbil baris pertama:")
print(matrix_1d[0])

print("\nAmbil baris keempat:")
print(matrix_1d[4])

print("\nAmbil 2 baris pertama:")
print(matrix_1d[0:2])

print("\nAmbil baris ke 1 sampai ke 4:")
print(matrix_1d[1:5])


Ambil baris pertama:
3

Ambil baris keempat:
6

Ambil 2 baris pertama:
[3 1]

Ambil baris ke 1 sampai ke 4:
[1 1 2 6]


In [20]:
# Matrix 2D

print("Ambil baris pertama:")
print(matrix[0])

print("\nAmbil kolom kedua:")
print(matrix[:, 1])

print("\nAmbil 2 kolom pertama:")
print(matrix[:, :2])

Ambil baris pertama:
[3 1 1]

Ambil kolom kedua:
[1 6]

Ambil 2 kolom pertama:
[[3 1]
 [2 6]]
